### ISSUE TITLE
Custom template.yaml where is saved and how can i select it from component inspector 

### ISSUE THREAD

**Issue by queengab** [linkonoid/oc-schemamarkup#1] opened 2021-04-12 15:30 UTC
Hi!
Good afternoon, i'm Gabriele from Italy.
Recently i found your plugin and i say: finally a plugin for schema.org for Octboer CMS

Now i've created a new yaml template for a blog post

`
_type: BlogPosting
"mainEntityOfPage": 
    "@type": "WebPage"
    "@id": "{{ ''|app }}"
"headline": "{{ post.title }}"
"description": "{{ post.excerpt }}"
"image": 
    "{{ image.path }}" 
"author": 
    "@type": "Person"
    "name": "Name"  
"publisher": 
    "@type": "Organization"
    "name": "Name"
    "logo": 
      "@type": "ImageObject"
      "url": "https://www.mysite/logo.svg"
"datePublished": "{{ post.published_at | strftime('%d.%m.%Y')}}"
"dateModified": "{{ post.updated_at | strftime('%d.%m.%Y')}}"
`

But wher the template is saved?
I haven't insert a default folder but it's not necessary i think, then i 'd like to add the component to show schema.org ld json
When i add the component to my partial i can choose the default templates but not my templates, why?

**Comment by linkonoid** [comment] 2021-04-12 16:17
Hi!

Yaml is validated on save. Most likely, Yaml - not valid. The priorities of the paths when saving are as follows (from the plugin description):
a) Custom path in Settings
b) /temlates/activeTheme/schemas
c) /plugins/linkonoid/schemamarkup/schemas

Since you did not specify anything, the path will be "/plugins/linkonoid /schemamarkup/schemas" (and yes - all the schemas in the delivery are test and it is advisable not to use them, they are for an example of defining a schema in Yaml format, but not for production, just rub them)

As for Yaml itself. It needs to be split into several schemes/files (unfortunately I don't have the original, so I might be wrong), something like this:

```
_type: BlogPosting
mainEntityOfPage: _WebPage

_type: WebPage
"@id": "{{  ''|app }}"
headline: "{{ post.title }}"
description: "{{ post.excerpt }}"
image: "{{ image.path }}"
author: _Person
publisher: _Organization

_type: Person
name: Name

_type: Organization
name: Name
logo: _ImageObject

_type: ImageObject
url: "https://www.mysite/logo.svg"
datePublished: "{{ post.published_at | strftime('%d.%m.%Y')}}"
dateModified: "{{ post.updated_at | strftime('%d.%m.%Y')}}"
```

The main concept of the plugin is to reuse the given schemes as much as possible in other projects.

**Comment by linkonoid** [comment] 2021-04-12 16:27
Unfortunately, I have little free time to adapt ready-made schemes (I am intensively working on a series of unique plugins for OctoberCMS).
I think you have already figured it out - everything is quite simple. You can even run the online converter json->yaml and change '@type' to '_type'

**Comment by linkonoid** [comment] 2021-04-12 16:31
Notice the "&" - is the nested schema pointer when rendering.

**Comment by queengab** [comment] 2021-04-16 07:52
Hi @linkonoid ,

thanks very much for your ready response.

So Understand all that's ok! 
Only one thing. It could be better if the component could load a custom yaml and not a series of yaml.

In my case for example i shall create many different yaml and insert one component for each yaml in my post layout or create a partial witll all components. It's a little bit hard. These are talks about the future, i understand you're now focused on developing products for the new OctoberCMS versions.

One more thing. In my new productnio environment i installed OctboerCMS 472 (version 1.1.3) that is free yet.
When i try to installa your plugin the plugin search bar can't find your plugin why?
Did i have to installa it from github with `php artisan` instead?

Thanks anyway!
Bye

**Comment by linkonoid** [comment] 2021-04-16 09:14
Hi @queengab,
You do not need to load a series of Yaml components in the layout, you just need to add the main Schema to the layout, and all the other nested ones with the "&" prefix are rendered automatically (regardless of the number and levels of schema nesting), this is the one from main essence of the plugin.
Regarding OctboerCMS 472. I tested the plugin on 471 a couple of days ago. I will definitely test the installation (this is probably due to the definition of the plugin in the yaml file).
OctoberCMS is getting to paid? I just don't follow events. Or have I misunderstood you?

**Comment by linkonoid** [comment] 2021-04-16 09:23
Perhaps I misunderstood your question a little, you can also bring everything to one Yaml without defining nested schemas:

```
_type: BlogPosting
mainEntityOfPage:
  "@id": "{{  ''|app }}"
  headline: "{{ post.title }}"
  description: "{{ post.excerpt }}"
  image: "{{ image.path }}"
  author:
    name: Name
  publisher: &Organization
    name: Name
    logo:
      url: "https://www.mysite/logo.svg"
      datePublished: "{{ post.published_at | strftime('%d.%m.%Y')}}"
      dateModified: "{{ post.updated_at | strftime('%d.%m.%Y')}}"
```

**Comment by queengab** [comment] 2021-04-16 16:06
Hi @linkonoid ,

many thanks for your quick responses. You are very kind!
So yes fundamentally my aim is to insert inside all blogpost a schema.org with multimple yaml. Now i understand the philosophy of your plugin

So i have in my case take the blogposting_schema and join the other with & cause i need this:

```
_type: BlogPosting
mainEntityOfPage: &WebPage

_type: WebPage
"@id": "{{  ''|app }}"
headline: "{{ post.title }}"
description: "{{ post.excerpt }}"
image: "{{ image.path }}"
author: &Person
publisher: &Organization

_type: Person
name: Name

_type: Organization
name: Name
logo: &ImageObject

_type: ImageObject
url: "https://www.mysite/logo.svg"
datePublished: "{{ post.published_at | strftime('%d.%m.%Y')}}"
dateModified: "{{ post.updated_at | strftime('%d.%m.%Y')}}"
```


> Regarding OctboerCMS 472. I tested the plugin on 471 a couple of days ago. I will definitely test the installation (this is probably due to the definition of the plugin in the yaml file).
> OctoberCMS is getting to paid? I just don't follow events. Or have I misunderstood you?

Yes beware many thins are changing: https://octobercms.com/blog/post/october-cms-moves-become-paid-platform 
Read all, they are updating market updating so now some plugin are not updatable by backend but only with composer or git

**Comment by linkonoid** [comment] 2021-04-16 17:31
Ok. I am always ready to help. Plugin documentation is somewhat sparse (the only schema example in the description is not very good). But since the plugin is free, I think it's somewhat forgivable.

As for the change of licensing. It discouraged me a lot. This is very bad for the development of CMS and many developers will be forced to go to alternative solutions. It is unacceptable when the rules of the game change so drastically.

**Comment by queengab** [comment] 2021-04-20 16:24
Hi @linkonoid ,

pardon me for late response! You sare so pleasant!
So it' true OctoberCms is now a paid platfomr from 2.0 version.


> As for the change of licensing. It discouraged me a lot. This is very bad for the development of CMS and many developers will be forced to go to alternative solutions. It is unacceptable when the rules of the game change so drastically.

I know it's like enter the superleague or remain inside Champions league :)
Luketower created a fork, WinterCMS https://github.com/wintercms. I think it could be a good alternative.


Intead a made some tries with your plugin:

I encountered in this fdays to main problem:

1) i insert some yaml in the settings section, ok? Then i change the directory and want then to save my yaml templates inside schemas folder in theme. I lost the file during the passage. Surely i made some mistake but i don't know which :)
2) Also the component is not updating very well and after some times i understand that shows the yaml templates based on _type and not based on template.yaml file 
3) I try to concatenate 2 yaml as you suggest. But when i try to join

```
_type: BlogPosting
mainEntityOfPage: &WebPage

_type: WebPage
"@id": "{{  ''|app }}"
headline: "{{ post.title }}"
description: "{{ post.excerpt }}"
image: "{{ image.path }}"
```

the plugin print his output: 
`<script type="application/ld+json">{"@context":"https://schema.org","@type":"BlogPosting","BlogPosting":{"mainEntityOfPage":null}}</script>  `

Don't understand why write two time "BlogPosting" and then null.

Maybe in general i noticed some problems whe you save or update yaml. Where the data are storage? There sometinh paramter on the db? 

Anywat thanks very much. It's normal is the first step in a new world. I'm thinking to create a unique plugin for seo, wtih facebook og:image, schemar.org, sitemap and robots.txt settings. I'm not a developer as you can imagine but a SEO guy but have an OctoberCMS plugin to start :)

Bye

**Comment by linkonoid** [comment] 2021-04-21 09:35
Hi @queengab,

1. When changing the directory in the settings (or the location path to the theme directory, without specifying in the settings), the files are not automatically transferred, they need to be manually copied to a new location (just move the folder, I previously wrote about the priorities of the paths in the settings; if uvas is explicitly set the path in the settings - it is processed first, if not specified, then the directory with the schemes in this plugin is searched first, then the directory of the same name in the current theme.
2. I do not quite understand the question. There may be a problem with the caching of the original file data (you can try to change the cache lifetime or re-save the schemes, when saving, the cache is reset).
3. Yes, there is a problem, I will try to fix it as soon as possible. I tested the schemas at https://schemamarkup.test.linkonoid.com/ (the schemas are in the settings). The value specified only through key / value is displayed normally. I have not yet figured out what the problem with attachments is. And, yes, thanks for the "@type": "BlogPosting", "BlogPosting": {" (didn't notice when testing).

The plugin is new, so such problems will still come up. This is normal. As a rule, on free projects, time is very limited and testing is done very superficially.

**Comment by queengab** [comment] 2021-04-21 11:01
Hi @linkonoid ,

first of all i want to thank you for sharing your plugin. It's normal and obvisuoly that a free plugin can't be perfect. So this is the reason person like me want to help you :). So please use me, if you want to test and develop the plugin if you want so. I like very much the idea behind you product! This is the right way.

And for the you point:

>  1) When changing the directory in the settings (or the location path to the theme directory, without specifying in the settings), the files are not automatically transferred, they need to be manually copied to a new location (just move the folder, I previously wrote about the priorities of the paths in the settings; if uvas is explicitly set the path in the settings - it is processed first, if not specified, then the directory with the schemes in this plugin is searched first, then the directory of the same name in the current theme.

You were clear about that. But i' experiecning problem in this case. I Tried to copy the yaml in my custom plujgin inside mytheme/schemas folder. The first time works well. Then i i changed the directory i reused the plugin directory and then go back and lost the files. I have to redo step by step the process to bring to you.


> 2) I do not quite understand the question. There may be a problem with the caching of the original file data (you can try to change the cache lifetime or re-save the schemes, when saving, the cache is reset). 

I think it's related to the first. When i inserted the component inside the page the dorp down let me choose only schemas that was previuosly loaded but not those were uploaded 5 seconds before. I tried to clear cache with `php artisan` and also browser cache. Don't know but surely was my mistake and don't done the correct steps

> 3) Yes, there is a problem, I will try to fix it as soon as possible. I tested the schemas at https://schemamarkup.test.linkonoid.com/ (the schemas are in the settings). The value specified only through key / value is displayed normally. I have not yet figured out what the problem with attachments is. And, yes, thanks for the "@type": "BlogPosting", "BlogPosting": {" (didn't notice when testing).

You're welcome. Please write to me if you want to test. I tried to read your class and understand how you concatenate with & but don't understand very much :)


Thanks again and bye!

**Comment by linkonoid** [comment] 2021-04-21 13:36
I solved the problem of nested rendering (corrected a couple of lines of code). In addition, it was necessary to enclose "&SchemaName" in quotes (I missed this point, since the "_" symbol was previously used, as and for "_type", after changing it to "&" I simply did not check, or rather did not notice the problem due to for the cache).

As for the preservation of the schemes. This is a difficult situation. Can not reproduce. Just save/duplicate schema files when you change their location (if you are not working through Git). This is due to the fact that the plugin uses a very non-trivial mechanism for saving data from widgets to a file (it could have been done without them - to the database, but then there would be no flexibility and the ability to edit files with an external editor, copy files, etc.)

Now I have another problem - I cannot upload it to the October marketplace - writes about an error in the composer ("Plugin name" linkonoid / oc-schemamarkup "is invalid, the expected value is" linkonoid / schemamarkup-plugin "for the" name " field. Please check the composer.json file and try again. ":) ...

**Closed** 2021-05-12 11:20 UTC
